# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLogIn(object):
    def setupUi(self, DialogLogIn):
        DialogLogIn.setObjectName("DialogLogIn")
        DialogLogIn.resize(360, 130)
        DialogLogIn.setMinimumSize(QtCore.QSize(360, 130))
        DialogLogIn.setMaximumSize(QtCore.QSize(360, 130))
        self.gridLayout = QtWidgets.QGridLayout(DialogLogIn)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditLogin = QtWidgets.QLineEdit(DialogLogIn)
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.gridLayout.addWidget(self.lineEditLogin, 0, 0, 1, 1)
        self.lineEditPassword = QtWidgets.QLineEdit(DialogLogIn)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout.addWidget(self.lineEditPassword, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogLogIn)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(DialogLogIn)
        self.buttonBox.accepted.connect(DialogLogIn.accept)
        self.buttonBox.rejected.connect(DialogLogIn.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogLogIn)

    def retranslateUi(self, DialogLogIn):
        _translate = QtCore.QCoreApplication.translate
        DialogLogIn.setWindowTitle(_translate("DialogLogIn", "LogIn"))
        self.lineEditLogin.setText(_translate("DialogLogIn", "domain\\"))
